# Generated by Django 3.2.22 on 2023-10-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counted_views',
        ),
    ]
